version: 2
jobs:
  build:
    working_directory: ~/punkhop/peetguercio.com
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "ea:21:ea:ec:db:21:3f:1f:3b:78:bc:2b:46:6b:d8:66"
    - deploy:
        command: |
          sudo apt-get install -y s3cmd
          echo "[default]" > ~/.s3cfg
          echo "access_key = $AWS_ACCESS_KEY_ID" >> ~/.s3cfg
          echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> ~/.s3cfg
          make deploy
